#!/bin/sh
# Wrapper to run CUPL.EXE (via 5vcomp) in the wine_atmel environment
# https://github.com/bkw777/ATF150x_uDEV/blob/main/programming.md
# Install in ~/.local/bin along with wine_atmel and 5vcomp

# hide $@ from wine_atmel so it doesn't try to run wine itself
ARGS="$@"
shift $#
. wine_atmel
5vcomp "${ARGS}"
