#!/bin/sh
# Wrapper to run CUPL.EXE (via 5vcomp) in the wine_atmel environment
# https://github.com/bkw777/ATF150x_uDEV/blob/main/programming.md
# Install in ~/.local/bin along with wine_atmel and 5vcomp

. wine_atmel
5vcomp "$@"
