#!/bin/bash
# Convenience script to load a specific WINEARCH & WINEPREFIX
# https://github.com/bkw777/ATF150x_uDEV/blob/main/programming.md
# Install in ~/.local/bin

# usage:
# 	$ . wine_atmel		# to set the wine env in your current shell environment
#	$ wine_atmel args...	# to run args... in the wine env
#	$ wine_atmel explorer
#	# wine_atmel "c:/path/to/file.exe" args...
(($#)) || set -x
export WINEARCH=win32 WINEPREFIX=~/.wine_atmel WINEDEBUG="fixme-hid,fixme-ntdll,fixme-imm"
(($#)) || set +x
(($#)) && wine "$@"
